language: node_js
node_js:
  - "node"
cache:
    directories:
     - /node_modules
script:
  - npm run test:ci        
before_deploy:
  - npm build  
deploy:
  provider: surge
  project: ./public/
  domain: valeriavg.surge.sh
  on: master  