language: node_js
node_js:
  - "node"
script:
  - npm run test:ci        
before_deploy:
  - npm run build  
deploy:
  skip_cleanup: true
  provider: surge
  project: ./public/
  domain: valeriavg.surge.sh
  on: master  